msm: Fix the build
This header is included outside of arch/arm/mach-msm; move it
somewhere preferable and define the proper include  path, so that
define_trace will always include the right header.

Fixes:
  fatal error: ./perf_trace_counters.h: No such file or directory

Change-Id: I0cabdfa7067408b7b8ce5a884b81aa69e9753ed8
Signed-off-by: Luis Cruz <ljc2491@gmail.com>